---
- name: Install Teleport binary
  ansible.builtin.shell: |
    curl https://cdn.teleport.dev/install.sh | bash -s {{ teleport_version }}

- name: Generate initial teleport.yaml
  ansible.builtin.shell: >
    teleport configure -o file
    --acme --acme-email={{ teleport_email }}
    --cluster-name={{ teleport_cluster_name }}
  args:
    creates: "{{ teleport_config_file }}"
